apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: default #修改
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
      - name: mongodb-exporter
        image: donglog/mongodb-exporter:latest
        ports:
        - containerPort: 8080
          name: http-metrics
        env:
        - name: MONGODB_URI
          value: "mongodb://账号:密码@ip:端口/?authSource=admin"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: default #修改
  labels:
    app: mongodb-exporter
spec:
  selector:
    app: mongodb-exporter
  ports:
  - name: http
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  type: ClusterIP #修改
